import { useRouter } from "next/router";
import {
  Group,
  Stack,
  Center,
  useMantineTheme,
  ScrollArea,
} from "@mantine/core";
import React, { useEffect, useState } from "react";
import { ArtworkType } from "../../../data-type/artwork";
import { getArtwork } from "../../../lib/api";
import Head from "next/head";
import { IconX } from "@tabler/icons-react";
import { ImageLocal } from "../../../components/Image/ImageLocal";
import { Prompt } from "../../../components/Art/Prompt";
import { ArtworkInfo } from "../../../components/Art/Info";

export default function ArtworkDetail() {
  const router = useRouter();
  const theme = useMantineTheme();

  const [artwork, setArtwork] = useState<ArtworkType | null>(null);

  useEffect(() => {
    const { artworkId } = router.query;
    if (!artworkId) {
      return;
    }
    if (Array.isArray(artworkId)) {
      return;
    }

    getArtwork(parseInt(artworkId)).then((resp) => setArtwork(resp));
  }, []);

  if (!artwork) {
    return <></>;
  }
  return (
    <>
      <Head>
        <title>{`Artwork generated by: ${artwork.card_name}`}</title>
      </Head>
      <Group
        style={{
          position: "relative",
        }}
        align={"start"}
      >
        <Stack>
          <Center m={40} bg={theme.colors.waLight[1]}>
            <ImageLocal
              localPath={artwork.file_path}
              width={450}
              height={600}
              objectFit={"contain"}
            />
          </Center>
          <ArtworkInfo artwork={artwork} />
        </Stack>

        <Stack style={{ position: "relative" }}>
          <ScrollArea
            scrollbars="y"
            scrollbarSize={2}
            bg={theme.colors.waLight[2]}
            h={`calc(100vh)`}
            w={500}
          >
            <Prompt
              cardName={artwork.card_name}
              inputsInfo={artwork.prompt.base_inputs}
              addonInputsInfo={artwork.prompt.addon_inputs}
            />
          </ScrollArea>
        </Stack>

        <Center
          bg={theme.colors.waLight[4]}
          style={{
            width: "40px",
            height: "40px",
            borderRadius: "25px",
            cursor: "pointer",
            position: "absolute",
            right: "150px",
            top: "10px",
            zIndex: 400,
          }}
          onClick={() => {
            router.back();
          }}
        >
          <IconX />
        </Center>
      </Group>
    </>
  );
}
